### ISSUE TITLE
Rename to `brainglobe-atlasapi`

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasapi#176]
The names of tools are inconsistent, and `bg` isn't very informative. We agreed in the [last dev meeting](https://github.com/brainglobe/BrainGlobe/discussions/350) to move to `brainglobe-xyz` as a standard.

**Comment by adamltyson** [comment]
But also see https://github.com/brainglobe/BrainGlobe/issues/43

**Comment by willGraham01** [comment]
Given https://github.com/brainglobe/BrainGlobe/issues/43, it seems logical that this happens at the same time as the merge so that we don't end up publishing another package to PyPI only to deprecate it seconds later.

Closing this and moving the content to https://github.com/brainglobe/BrainGlobe/issues/43 as an additional task
