### ISSUE TITLE
kim_unified_25um has some errors

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-atlasapi#72]
There seems to be two major errors:
* The annotations and reference images are not aligned. The reference image also isn't aligned with the allen 25um atlas which it probably should be.
* There are border regions in the annotation image with incorrect values.

**Comment by vigji** [comment]
Is it because of pre-processing or some previously overlooked mismatches in the source data?

In any case, I would suggest to address this and potentially anything related to atlases in the context of the refactoring that is happening in #60 to go toward automatised atlas generation. The general script structure has changed but I refactored only fish, example, and allen; kim and human should follow to have everything at the same stage.

I would like to finish that before submitting, should not be too much work!

**Comment by adamltyson** [comment]
Not sure. The border regions are definitely reprocessing though, they aren't in the raw data I have.

Agree, it would be much better to wait for #60, then edit the atlases. As it is, it's a surprising amount of work to get everything updated just to fix little things.

**Comment by adamltyson** [comment]
Not sure, maybe we made an assumption about the original data that wasn't correct? I think it's just the orientation that's wrong
